### ISSUE TITLE
RecovAr interrpted with exception: "Cannot read field 'entities' because 'c' is null".

### ISSUE THREAD

**Issue by WGC575** [usc-softarch/arcade_core#104]
**Problem Description**
I ran into this problem when I ran RecovAr on project mkvtoolnix (ID 4910441), and the program seems to stop at the same point (after the 284-th request) and will give an error (Cannot read field "entities" because "c" is null).
The issueCheckpoint file seems to be processed correctly, but the output of method getDecisionList() returns empty collections for all versions of MKVToolNix.
By the way, RecovAr runs correctly now on GraphViz after fixing the API entry problem.

**To Reproduce**
Run the following command in PowerShell:
```console
java -cp ARCADE_Core.jar edu.usc.softarch.arcade.facts.design.RecovArEngine "./clusters/mkvtoolnix/acdc" "./versionTree_mkvtoolnix.rsf" 4910441 "./issuesChec
kpoint_mkvtoolnix.json" "(\\d+(\\.\\d+)?(\\.\\d+)?(\\.\\d+)?(-?(alpha(\\d+)?|beta(\\d+)?|rc(\\d+)?|pre(\\d+)?)?))*" "./recovArOutput.json"
```
[Here are the necessary resources to run the command](https://drive.google.com/file/d/1OELjtfg4OZgjKnvQdwzjWCSMuzvR6rei/view?usp=sharing):
- clusters from acdc
- versionTree.rsf
- ARCADE_core.jar (with one of the bug fixed)
- issuesCheckpoint_mkvtoolnix_acdc.json (which has been process until 3400 issues, with ~3600 in total)

**Additional Debugging Information**
The error happened when processing issue 3629 for version 6.8.0.

**The PowerShell log**
```console
PS D:\Workspace\arc-sum\scripts\ARCADE> java -cp ARCADE_Core.jar edu.usc.softarch.arcade.facts.design.RecovArEngine "./clusters/mkvtoolnix/acdc" "./versionTree.rsf" 4910441 "./issuesCheckpoint.json" "(\\d+(\\.\\d+)?(\\.\\d+)?(\\.\\d+)?(-?(alpha(\\d+)?|beta(\\d+)?|rc(\\d+)?|pre(\\d+)?)?))*" "./recovArOutput.json"
2023/10/24 21:40:43: Started processing issues for project ID 4910441
No record located, running full scan.
2023/10/24 21:41:34: Finished processing 100 issues.
2023/10/24 21:41:51: Finished processing 200 issues.
Exception in thread "main" edu.usc.softarch.arcade.facts.issues.handlers.GitLabRestHandler$GitLabRestHandlerException of 284 HTTP requests sent. Please report this exception. Local exception message was: New field identified: prepared_at, in issue ID: 2245
        at edu.usc.softarch.arcade.facts.issues.handlers.GitLabRestHandler.throwLocalException(GitLabRestHandler.java:49)
        at edu.usc.softarch.arcade.facts.issues.handlers.GitLabRestHandler.parseCommit(GitLabRestHandler.java:478)  
        at edu.usc.softarch.arcade.facts.issues.handlers.GitLabRestHandler.processCommits(GitLabRestHandler.java:369)        at edu.usc.softarch.arcade.facts.issues.handlers.GitLabRestHandler.parseIssue(GitLabRestHandler.java:342)    
        at edu.usc.softarch.arcade.facts.issues.handlers.GitLabRestHandler.processIssues(GitLabRestHandler.java:219)
        at edu.usc.softarch.arcade.facts.issues.handlers.GitLabRestHandler.getIssueRecords(GitLabRestHandler.java:123)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.<init>(RecovArEngine.java:69)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.runWithGitLab(RecovArEngine.java:45)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.main(RecovArEngine.java:21)
PS D:\Workspace\arc-sum\scripts\ARCADE> java -cp ARCADE_Core.jar edu.usc.softarch.arcade.facts.design.RecovArEngine "./clusters/mkvtoolnix/acdc" "./versionTree.rsf" 4910441 "./issuesCheckpoint.json" "(\\d+(\\.\\d+)?(\\.\\d+)?(\\.\\d+)?(-?(alpha(\\d+)?|beta(\\d+)?|rc(\\d+)?|pre(\\d+)?)?))*" "./recovArOutput.json"
2023/10/24 21:44:34: Started processing issues for project ID 4910441
Exception in thread "main" java.lang.NullPointerException: Cannot read field "entities" because "c" is null
        at edu.usc.softarch.arcade.clustering.data.ReadOnlyCluster.difference(ReadOnlyCluster.java:217)
        at edu.usc.softarch.arcade.facts.design.ElementChangeAnalyzer.getAddedElements(ElementChangeAnalyzer.java:34)        at edu.usc.softarch.arcade.facts.ChangeAnalyzer.initializeChangeList(ChangeAnalyzer.java:57)
        at edu.usc.softarch.arcade.facts.ChangeAnalyzer.getChangeList(ChangeAnalyzer.java:45)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:95)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
        at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
```

**Comment by WGC575** [comment]
I'm currently working on it.

**Comment by WGC575** [comment]
The problem "Cannot read field "entities" because "c" is null", where "c" is the cluster, means there is not valid cluster read into the difference() function.

**Comment by WGC575** [comment]
The problem seems to be similar to the one that occurs a few months ago. It's a new field potentially added to the API, which is supposed to be "prepared_at". Fixing it right now.

**Comment by WGC575** [comment]
I currently can push things to this repo. @MarceloLaser, do you have time to make the following changes:
- Add the following code block to ```GitLabRestHandler.java``` under method ```parseCommit(JsonParser parser)``` to recognize the new field "prepared_at":
```java
case "prepared_at":
	skipToNextField(parser);
	break;
```
- Differentiate the "new field identified" messages to make it clear which does the new field that is identified belong to.

**Comment by WGC575** [comment]
The "prepare_at" new field problem is fixed, but the "c is null" problem remains unsolved. Here is the log messages:

```console
D:\Workspace\JDK\openjdk-17.0.1\bin\java.exe "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\lib\idea_rt.jar=7762:D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\bin" -Dfile.encoding=UTF-8 -classpath D:\Workspace\arcade_core\target\classes;C:\Users\wgc57\.m2\repository\cc\mallet\mallet\local\mallet-local.jar;C:\Users\wgc57\.m2\repository\gnu\trove\trove\local\trove-local.jar;C:\Users\wgc57\.m2\repository\com\carrotsearch\hppc\0.9.1\hppc-0.9.1.jar;C:\Users\wgc57\.m2\repository\org\apache-extras\beanshell\bsh\2.0b6\bsh-2.0b6.jar;C:\Users\wgc57\.m2\repository\com\google\errorprone\error_prone_annotations\2.3.1\error_prone_annotations-2.3.1.jar;C:\Users\wgc57\.m2\repository\org\jgrapht\jgrapht-core\1.5.1\jgrapht-core-1.5.1.jar;C:\Users\wgc57\.m2\repository\org\jheaps\jheaps\0.13\jheaps-0.13.jar;C:\Users\wgc57\.m2\repository\com\googlecode\json-simple\json-simple\1.1.1\json-simple-1.1.1.jar;C:\Users\wgc57\.m2\repository\junit\junit\4.10\junit-4.10.jar;C:\Users\wgc57\.m2\repository\org\hamcrest\hamcrest-core\1.1\hamcrest-core-1.1.jar;C:\Users\wgc57\.m2\repository\net\rcarz\jira-client\0.5\jira-client-0.5.jar;C:\Users\wgc57\.m2\repository\org\apache\httpcomponents\httpclient\4.2.5\httpclient-4.2.5.jar;C:\Users\wgc57\.m2\repository\org\apache\httpcomponents\httpcore\4.2.4\httpcore-4.2.4.jar;C:\Users\wgc57\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;C:\Users\wgc57\.m2\repository\commons-codec\commons-codec\1.6\commons-codec-1.6.jar;C:\Users\wgc57\.m2\repository\org\apache\httpcomponents\httpmime\4.2.5\httpmime-4.2.5.jar;C:\Users\wgc57\.m2\repository\net\sf\json-lib\json-lib\2.4\json-lib-2.4-jdk15.jar;C:\Users\wgc57\.m2\repository\commons-beanutils\commons-beanutils\1.8.0\commons-beanutils-1.8.0.jar;C:\Users\wgc57\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\wgc57\.m2\repository\commons-lang\commons-lang\2.5\commons-lang-2.5.jar;C:\Users\wgc57\.m2\repository\net\sf\ezmorph\ezmorph\1.0.6\ezmorph-1.0.6.jar;C:\Users\wgc57\.m2\repository\joda-time\joda-time\2.3\joda-time-2.3.jar;C:\Users\wgc57\.m2\repository\org\mockito\mockito-all\1.9.0\mockito-all-1.9.0.jar;C:\Users\wgc57\.m2\repository\commons-httpclient\commons-httpclient\3.1\commons-httpclient-3.1.jar;C:\Users\wgc57\.m2\repository\com\thoughtworks\xstream\xstream\1.4.19\xstream-1.4.19.jar;C:\Users\wgc57\.m2\repository\io\github\x-stream\mxparser\1.2.2\mxparser-1.2.2.jar;C:\Users\wgc57\.m2\repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;C:\Users\wgc57\.m2\repository\org\bithill\classycle\1.4.4\classycle-1.4.4.jar;C:\Users\wgc57\.m2\repository\net\sourceforge\jexcelapi\jxl\2.6.12\jxl-2.6.12.jar;C:\Users\wgc57\.m2\repository\log4j\log4j\1.2.14\log4j-1.2.14.jar;C:\Users\wgc57\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.14.0\jackson-databind-2.14.0.jar;C:\Users\wgc57\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.14.0\jackson-annotations-2.14.0.jar;C:\Users\wgc57\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.14.0\jackson-core-2.14.0.jar;C:\Users\wgc57\.m2\repository\org\jetbrains\annotations\24.0.1\annotations-24.0.1.jar edu.usc.softarch.arcade.facts.design.RecovArEngine D:\Workspace\arc-sum\scripts\ARCADE\clusters\mkvtoolnix\acdc D:\Workspace\arc-sum\scripts\ARCADE\versionTree.rsf 4910441 D:\Workspace\arc-sum\scripts\ARCADE\issuesCheckpoint.json "(\\d+(\\.\\d+)?(\\.\\d+)?(\\.\\d+)?(-?(alpha(\\d+)?|beta(\\d+)?|rc(\\d+)?|pre(\\d+)?)?))*" D:\Workspace\arc-sum\scripts\ARCADE\recovArOutput.json
2023/10/28 22:31:11: Started processing issues for project ID 4910441
No record located, running full scan.
2023/10/28 22:31:58: Finished processing 100 issues.
2023/10/28 22:32:17: Finished processing 200 issues.
2023/10/28 22:32:38: Finished processing 300 issues.
2023/10/28 22:32:56: Finished processing 400 issues.
2023/10/28 22:33:13: Finished processing 500 issues.
2023/10/28 22:33:33: Finished processing 600 issues.
2023/10/28 22:33:52: Finished processing 700 issues.
2023/10/28 22:34:11: Finished processing 800 issues.
2023/10/28 22:34:31: Finished processing 900 issues.
2023/10/28 22:34:50: Finished processing 1000 issues.
2023/10/28 22:35:10: Finished processing 1100 issues.
2023/10/28 22:35:33: Finished processing 1200 issues.
2023/10/28 22:35:55: Finished processing 1300 issues.
2023/10/28 22:36:16: Finished processing 1400 issues.
2023/10/28 22:36:37: Finished processing 1500 issues.
2023/10/28 22:36:55: Finished processing 1600 issues.
2023/10/28 22:37:16: Finished processing 1700 issues.
2023/10/28 22:37:36: Finished processing 1800 issues.
2023/10/28 22:37:56: Finished processing 1900 issues.
2023/10/28 22:38:16: Finished processing 2000 issues.
2023/10/28 22:38:35: Finished processing 2100 issues.
2023/10/28 22:38:53: Finished processing 2200 issues.
2023/10/28 22:39:12: Finished processing 2300 issues.
2023/10/28 22:39:30: Finished processing 2400 issues.
2023/10/28 22:39:49: Finished processing 2500 issues.
2023/10/28 22:40:10: Finished processing 2600 issues.
2023/10/28 22:40:29: Finished processing 2700 issues.
2023/10/28 22:40:48: Finished processing 2800 issues.
2023/10/28 22:41:11: Finished processing 2900 issues.
2023/10/28 22:41:31: Finished processing 3000 issues.
2023/10/28 22:41:56: Finished processing 3100 issues.
2023/10/28 22:42:23: Finished processing 3200 issues.
2023/10/28 22:42:45: Finished processing 3300 issues.
2023/10/28 22:43:07: Finished processing 3400 issues.
Exception in thread "main" java.lang.NullPointerException: Cannot read field "entities" because "c" is null
	at edu.usc.softarch.arcade.clustering.data.ReadOnlyCluster.difference(ReadOnlyCluster.java:217)
	at edu.usc.softarch.arcade.facts.design.ElementChangeAnalyzer.getAddedElements(ElementChangeAnalyzer.java:34)
	at edu.usc.softarch.arcade.facts.ChangeAnalyzer.initializeChangeList(ChangeAnalyzer.java:57)
	at edu.usc.softarch.arcade.facts.ChangeAnalyzer.getChangeList(ChangeAnalyzer.java:45)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:95)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.loadDecisions(RecovArEngine.java:97)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.getDecisions(RecovArEngine.java:77)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.runWithGitLab(RecovArEngine.java:48)
	at edu.usc.softarch.arcade.facts.design.RecovArEngine.main(RecovArEngine.java:21)
```
